import { 
  quartic, 
  molex, 
  coderise, 
  tulip,
  boeing, 
} from "../assets";

const experiences = [
    {
      id: 1,
      title: "Full Stack Engineer (Co-op)",
      company_name: "Quartic.Ai",
      company_url: "https://www.quartic.ai/",
      location: "Toronto, Canada",
      icon: quartic,
      iconbg: "#fff",
      date: "May 2021 - Aug 2021",
      descriptions: [],
      achievements: [],
    },
    {
      id: 2,
      title: "Software Developer In Test (Co-op)",
      company_name: "Molex",
      company_url: "https://www.molex.com/en-us/home",
      location: "Waterloo, Canada",
      icon: molex,
      iconbg: "#fff",
      date: "Jan 2022 - Aug 2022",
      descriptions: [],
      achievements: [],
    },
    {
      id: 3,
      title: "Software Developer (Intern)",
      company_name: "CodeRise Technologies",
      company_url: "https://coderise.io/",
      location: "Brampton, Canada",
      icon: coderise,
      iconbg: "#fff",
      date: "Jul 2023 - Aug 2023",
      descriptions: [],
      achievements: [],
    },
    {
      id: 4,
      title: "QA Engineer (Co-op)",
      company_name: "Tulip",
      company_url: "https://www.tulip.com/",
      location: "Kitchener, Canada",
      icon: tulip,
      iconbg: "#fff",
      date: "Sept 2023 - Dec 2023",
      descriptions: [],
      achievements: [],
    },
    {
      id: 5,
      title: "Software Application Developer",
      company_name: "Boeing",
      company_url: "https://www.boeing.ca/",
      location: "Montreal, Canada",
      icon: boeing,
      iconbg: "#fff",
      date: "Dec 2024 - Present",
      descriptions: [],
      achievements: [],
    },

  ];
  
  export { experiences };